[project]
name = "chzzkchat"
version = "0.1.0"
description = "치지직(Chzzk) 실시간 채팅 뷰어"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.80.5",
    "requests",
    "websockets>=16.0",
]

[tool.flet]
app.path = "src"
app.assets_dir = "src/assets"
